#!/bin/bash
# .openshift/action_hooks/deploy

( ln -s ${OPENSHIFT_DATA_DIR}.env ${OPENSHIFT_REPO_DIR}.env )
( cd ${OPENSHIFT_REPO_DIR} ; composer install --no-interaction --no-dev )
( cd ${OPENSHIFT_REPO_DIR} ; touch ${OPENSHIFT_DATA_DIR}database.sqlite; php artisan down ; php artisan migrate --force ; php artisan up )