#!/bin/bash
# .openshift/action_hooks/deploy

( rm $OPENSHIFT_REPO_DIR.env; ln -s $OPENSHIFT_DATA_DIR.env $OPENSHIFT_REPO_DIR.env )
( cd $OPENSHIFT_REPO_DIR ; composer install --no-interaction --no-dev )